apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: kalyn-qcgit1
  project: kalyn-gitops24
spec:
  blueprintConfig:
    name: default
  cloudCredentials: awscressss
  cniProvider: aws-cni
  config:
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
      instanceType: t3.xlarge
      maxSize: 2
      minSize: 1
      name: ng1
      volumeSize: 80
      volumeType: gp3
    - amiFamily: AmazonLinux2
      desiredCapacity: 1
      iam:
        withAddonPolicies:
          autoScaler: true
      instanceType: t3.xlarge
      maxSize: 2
      minSize: 1
      name: ngroup4
      volumeSize: 80
      volumeType: gp3
    metadata:
      name: kalyn-qcgit1
      region: us-west-2
      version: "1.22"
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: false
        publicAccess: true
      nat:
        gateway: Single
  proxyConfig: {}
  type: aws-eks
